baseURL = 'https://loic.lescoat.me/'
languageCode = 'en-us'
title = "Lo√Øc's website"
theme = 'papermod'

[params]
disableSpecial1stPost = true

[params.profileMode]
enabled = true
title = "Welcome to my website!"

[[params.profileMode.buttons]]
name = "Read blog posts"
url = "/blog/"

[[params.profileMode.buttons]]
name = "Learn line dances"
url = "/linedance-tracker/"

[[menu.main]]
name = "Blog"
url = "/blog/"
